
services:
  postgres:
    image: postgres:15
    container_name: hackeps_docker_postgre
    environment:
      POSTGRES_USER: root     
      POSTGRES_PASSWORD: hackeps   
      POSTGRES_DB: parking_hackeps  
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

